PartsUnlimited/PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace PartsUnlimited.Models
{
    public partial class ShoppingCart
    {
        private readonly IPartsUnlimitedContext _db;
        string ShoppingCartId { get; set; }

        public ShoppingCart(IPartsUnlimitedContext db)
        {
            _db = db;
        }

        public static ShoppingCart GetCart(IPartsUnlimitedContext db, HttpContextBase context)
        {
            var cart = new ShoppingCart(db);
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }

        public void AddToCart(Product product)
        {
            // Get the matching cart and product instances
            var cartItem = _db.CartItems.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.ProductId == product.ProductId);

            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new CartItem
                {
                    ProductId = product.ProductId,
                    CartId = ShoppingCartId,
                    Count = 1,
                    DateCreated = DateTime.Now
                };

                _db.CartItems.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, then add one to the count
                cartItem.Count++;
            }
        }

        public int RemoveFromCart(int id)
        {
            // Get the cart
            var cartItem = _db.CartItems.Single(
                cart => cart.CartId == ShoppingCartId
                && cart.CartItemId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    _db.CartItems.Remove(cartItem);
                }
            }

            return itemCount;
        }

        public void EmptyCart()
        {
            var cartItems = _db.CartItems.Where(cart => cart.CartId == ShoppingCartId);
            foreach (var item in cartItems)
                _db.CartItems.Remove(item);
        }

        public List<CartItem> GetCartItems()
        {
            var cartItems = _db.CartItems.Where(cart => cart.CartId == ShoppingCartId).Include("Product").ToList();

            return cartItems;
        }

        public int GetCount()
        {
            int sum = 0;
            //https://github.com/aspnet/EntityFramework/issues/557
            // Get the count of each item in the cart and sum them up
            var cartItemCounts = (from cartItems in _db.CartItems
                                  where cartItems.CartId == ShoppingCartId
                                  select (int?)cartItems.Count);

            cartItemCounts.ForEachAsync(carItemCount =>
            {
                if (carItemCount.HasValue)
                {
                    sum += carItemCount.Value;
                }
            });

            // Return 0 if all entries are null
            return sum;
        }

        public decimal GetTotal()
        {
            // Multiply product price by count of that product to get 
            // the current price for each of those products in the cart
            // sum all product price totals to get the cart total
            decimal total = 0;
            foreach (var item in _db.CartItems.Include("Product").Where(c => c.CartId == ShoppingCartId))
            {
                total += item.Count * item.Product.Price;
            }

            return total;
        }

        public int CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartItems = GetCartItems();

            // Iterate over the items in the cart, adding the order details for each
            foreach (var item in cartItems)
            {
                //var product = _db.Products.Find(item.ProductId);
                var product = _db.Products.Single(a => a.ProductId == item.ProductId);

                var orderDetail = new OrderDetail
                {
                    ProductId = item.ProductId,
                    OrderId = order.OrderId,
                    UnitPrice = product.Price,
                    Count = item.Count,
                };

                // Set the order total of the shopping cart
                orderTotal += (item.Count * product.Price);

                _db.OrderDetails.Add(orderDetail);
            }

            // Set the order's total to the orderTotal count
            order.Total = orderTotal;

            // Empty the shopping cart
            EmptyCart();

            // Return the OrderId as the confirmation number
            return order.OrderId;
        }

        // We're using HttpContextBase to allow access to cookies.
        public string GetCartId(HttpContextBase context)
        {
            var sessionCookie = context.Request.Cookies.Get("Session");
            string cartId = null;

            if (sessionCookie == null)
            {
                //A GUID to hold the cartId. 
                cartId = Guid.NewGuid().ToString();

                // Send cart Id as a cookie to the client.
                context.Response.Cookies.Add(new HttpCookie("Session", cartId));
            }
            else
            {
                cartId = sessionCookie.Value;
            }

            return cartId;
        }
    }
}

PartsUnlimited/PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/ViewModels/ShoppingCartViewModel.cs
using System.Collections.Generic;
using PartsUnlimited.Models;

namespace PartsUnlimited.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<CartItem> CartItems { get; set; }
        public int CartCount { get; set; }
        public OrderCostSummary OrderCostSummary { get; set; }
    }
}

PartsUnlimited/PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;
using PartsUnlimited.Models;
using PartsUnlimited.Utils;
using PartsUnlimited.ViewModels;

namespace PartsUnlimited.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IPartsUnlimitedContext db;
        private readonly ITelemetryProvider telemetry;
        private readonly IShippingTaxCalculator shippingTaxCalculator;

		public ShoppingCartController(IPartsUnlimitedContext context, ITelemetryProvider telemetryProvider, 
			IShippingTaxCalculator shippingTaxCalc)
        {
            db = context;
            telemetry = telemetryProvider;
			shippingTaxCalculator = shippingTaxCalc;
        }

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(db, HttpContext);
            var items = cart.GetCartItems();
			var itemsCount = items.Sum(x => x.Count);
			//var subTotal = items.Sum(x => x.Count * x.Product.Price);
			//var shipping = itemsCount * (decimal)5.00;
			//var tax = (subTotal + shipping) * (decimal)0.05;
			//var total = subTotal + shipping + tax;

			//var costSummary = new OrderCostSummary
			//{
			//    CartSubTotal = subTotal.ToString("C"),
			//    CartShipping = shipping.ToString("C"),
			//    CartTax = tax.ToString("C"),
			//    CartTotal = total.ToString("C")
			//};
			var costSummary = shippingTaxCalculator.CalculateCost(items, null);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = items,
                CartCount = itemsCount,
                OrderCostSummary = costSummary
            };


            // Track cart review event with measurements
            telemetry.TrackTrace("Cart/Server/Index");

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/AddToCart/5

        public async Task<ActionResult> AddToCart(int id)
        {
            // Retrieve the product from the database
            var addedProduct = db.Products
                .Single(product => product.ProductId == id);

            // Start timer for save process telemetry
            var startTime = DateTime.Now;

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(db, HttpContext);

            cart.AddToCart(addedProduct);

            await db.SaveChangesAsync(CancellationToken.None);

            // Trace add process
            var measurements = new Dictionary<string, double>()
            {
                {"ElapsedMilliseconds", DateTime.Now.Subtract(startTime).TotalMilliseconds }
            };
            telemetry.TrackEvent("Cart/Server/Add", null, measurements);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [System.Web.Mvc.HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveFromCart([FromUri] int id)
        {

            // Start timer for save process telemetry
            var startTime = DateTime.Now;

            // Retrieve the current user's shopping cart
            var cart = ShoppingCart.GetCart(db, HttpContext);

            // Get the name of the product to display confirmation
            var cartItem = db.CartItems.Include("Product").Single(item => item.CartItemId == id);
            string productName = cartItem.Product.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            await db.SaveChangesAsync(CancellationToken.None);

            string removed = (itemCount > 0) ? " 1 copy of " : string.Empty;

            // Trace remove process
            var measurements = new Dictionary<string, double>()
            {
                {"ElapsedMilliseconds", DateTime.Now.Subtract(startTime).TotalMilliseconds }
            };
            telemetry.TrackEvent("Cart/Server/Remove", null, measurements);

            // Display the confirmation message
            var items = cart.GetCartItems();
            var itemsCount = items.Sum(x => x.Count);
            var subTotal = items.Sum(x => x.Count * x.Product.Price);
            var shipping = itemsCount * (decimal)5.00;
            var tax = (subTotal + shipping) * (decimal)0.05;
            var total = subTotal + shipping + tax;

            var results = new ShoppingCartRemoveViewModel
            {
                Message = removed + productName +
                    " has been removed from your shopping cart.",
                CartSubTotal = subTotal.ToString("C"),
                CartShipping = shipping.ToString("C"),
                CartTax = tax.ToString("C"),
                CartTotal = total.ToString("C"),
                CartCount = itemsCount,
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }
    }
}

PartsUnlimited/PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Controllers/StoreController.cs
using PartsUnlimited.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Runtime.Caching;
using System.Web.Mvc;
using PartsUnlimited.Utils;
using PartsUnlimited.ViewModels;

namespace PartsUnlimited.Controllers
{
    public class StoreController : Controller
    {
        private readonly IPartsUnlimitedContext db;

        public StoreController(IPartsUnlimitedContext context)
        {
            db = context;
        }

        //
        // GET: /Store/
        public ActionResult Index()
        {
            var genres = db.Categories.ToList();

            return View(genres);
        }

        //
        // GET: /Store/Browse?genre=Disco
        public ActionResult Browse(int categoryId)
        {
            // Retrieve Category genre and its Associated associated Products products from database
            var genreModel = db.Categories.Include("Products").Single(g => g.CategoryId == categoryId);

            return View(genreModel);
        }

        public ActionResult Details(int id)
        {

            var productCacheKey = string.Format("product_{0}", id);
            var product = MemoryCache.Default[productCacheKey] as Product;
            if (product == null)
            {
                product = db.Products.Single(a => a.ProductId == id);
                //Remove it from cache if not retrieved in last 10 minutes
                MemoryCache.Default.Add(productCacheKey, product, new CacheItemPolicy { SlidingExpiration = TimeSpan.FromMinutes(10) });
            }
            var viewModel = new ProductViewModel
            {
                Product = product,
                ShowRecommendations = ConfigurationHelpers.GetBool("ShowRecommendations")
            };

            return View(viewModel);
        }

    }
}

PartsUnlimited/PartsUnlimited-aspnet45/src/PartsUnlimitedWebsite/Views/ShoppingCart/Index.cshtml
@model PartsUnlimited.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}

@functions
{
    public string GetAntiXsrfToken()
    {
        return Html.AntiForgeryToken().ToHtmlString();
    }
}

@section Scripts {
    <script type="text/javascript">
        $(function () {
            // Document.ready -> link up remove event handler
            $(".remove-link").click(function () {
                // Get the id from the link
                var recordToDelete = $(this).attr("data-id");
                var postToUrl = $(this).attr("data-url");
                if (recordToDelete != '') {
                    var form = $('#__AjaxAntiForgeryForm');
                    var token = $('input[name="__RequestVerificationToken"]', form).val();

                    // Perform the ajax post
                    $.post(postToUrl, { "id": recordToDelete, "__RequestVerificationToken": token },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            if (data.CartCount == 0) {
                                $('#cart-summary').hide();
                                $('#cart-count').hide();
                                $('#empty-cart').show();
                            } else {

                                if (data.ItemCount == 0) {
                                    $('#row-' + data.DeleteId).fadeOut('slow');
                                } else {
                                    $('#item-count-' + data.DeleteId).text(data.ItemCount);
                                }
                            }
                            $('#cart-sub-total').text(data.CartSubTotal);
                            $('#cart-shipping').text(data.CartShipping);
                            $('#cart-tax').text(data.CartTax);
                            $('#cart-total').text(data.CartTotal);
                            $('#update-message').text(data.Message);
                            $('#cart-status').text('Cart (' + data.CartCount + ')');
                            $('#cart-count').text(data.CartCount);
                        });
                }
            });

        });
    </script>
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "__AjaxAntiForgeryForm" }))
{
    @Html.AntiForgeryToken()
}

<div id="shopping-cart-page">
    <section>
        <h2>Review your Cart</h2>
        <div id="update-message">
        </div>
        @if (Model.CartCount > 0)
        {
            <div id="cart-summary">
                <div class="hidden-xs cart-summary-header">
                    <div class="row">
                        <div class="col-sm-8 col-md-8 no-gutter-md-left no-gutter-sm-left">Product Description</div>
                        <div class="col-sm-2 col-md-2 text-center">Quantity</div>
                        <div class="col-sm-2 col-md-2 text-center">Price</div>
                    </div>
                </div>

                @foreach (var item in Model.CartItems)
                {
                    <div id="row-@item.CartItemId" class="cart-item">
                        <div class="row">
                            <div class="col-xs-1 no-gutter-xs-right text-center-xs col-sm-2 col-sm-push-8 text-center-sm">
                                <div class="item-label item-inventory">@item.Count</div>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-sm-pull-2 col-md-2">
                                <img src="/Images/@item.Product.ProductArtUrl" alt="@item.Product.Title"/>
                            </div>
                            <div class="col-xs-6 col-sm-2 col-sm-push-5 text-center-sm col-md-push-6">
                                <div class="visible-xs item-label">@item.Product.Title</div>
                                <div class="item-price">@item.Product.Price.ToString("C")</div>
                            </div>
                            <div class="visible-xs col-xs-2 text-right no-gutter-xs-left">
                                <a href="#" class="remove-link" data-id="@item.CartItemId"
                                   data-url='@Url.Content("~/ShoppingCart/RemoveFromCart")'>
                                    <img src="/Images/remove_icon.png" alt="remove from cart icon" />
                                </a>
                            </div>
                            <div class="col-xs-12 col-sm-5 col-sm-pull-4 col-md-6 description">
                                <div class="hidden-xs"><strong>@Html.ActionLink(item.Product.Title, "Details", "Store", new { id = item.ProductId }, null)</strong></div>
                                <div class="visible-xs item-label">Description</div>
                                <p class="text-content">@item.Product.Description</p>
                            </div>
                            <div class="hidden-xs remove-cart-item">
                                <a href="#" class="remove-link btn" data-id="@item.CartItemId"
                                   data-url='@Url.Content("~/ShoppingCart/RemoveFromCart")'>
                                    Remove
                                </a>
                            </div>
                        </div>
                    </div>
                }

                @Html.Partial("_OrderCostsummary", Model.OrderCostSummary)
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-sm-offset-6 col-md-4 col-md-offset-8">
                        <div>
                            @Html.ActionLink("Checkout", "AddressAndPayment", "Checkout", null, new { @class = "btn pull-right checkout" })
                        </div>
                    </div>
                </div>
            </div>
        }
        <h4 id="empty-cart" @if (Model.CartCount > 0) { <text> style="display:none;" </text> }>Your cart is currently empty</h4>
    </section>
</div>